wechat:
  open:
    componentAppId: "wx5dfdb53d47174243"
    componentSecret: "14cb46f22e3f04a0add2d69d54a35131"
    componentToken: "1bf2aa9e0ea2ca584a8030ed707c342f5ce46e4f2a0fa0b23a8e7b99e263c694357b14b87ad48174cba3bddcfd8f47a8340fbdcbaa32a82a97a8403693bd5ca3"
    componentAesKey: "2c8accdf24f482cc08480ca1c0af09dd7fea5b1d3a2"
  redis:
    host: "127.0.0.1"
server:
  port: 8081

spring:
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/static/
    # 这个可以不配置，检查模板位置
    check-template-location: true
    # 下面3个不做解释了，可以不配置
    suffix: .html
    encoding: UTF-8
    content-type: text/html

    # 模板的模式
    mode: HTML5
  profiles:
    active: localhost
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: true
mybatis:
  type-aliases-package: com.github.binarywang.demo.wx.open.model


---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://35.199.186.132:3306/linqubator?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: linqubator
    password: 110119120

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://35.199.186.132:3306/linqubator?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: linqubator
    password: 110119120


---

spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/linqubator?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 110119120
logging:
  level:
    org:
      hibernate:
        SQL: debug
      mybatis:
        SQL: debug


